### ISSUE TITLE
AttributeError: '_DataLoaderIter' object has no attribute 'rcvd_idx'

### ISSUE THREAD

**Issue by panicwq** [nii-yamagishilab/Capsule-Forensics#1]
With my own dataset,
report an error.

runfile('D:/Panicwq/Capsule-Forensics-master/test.py', wdir='D:/Panicwq/Capsule-Forensics-master')
Namespace(batchSize=100, dataset='dataset', gpu_id=0, id=95, imageSize=128, outf='checkpoints', random=False, test_set='test', workers=1)

  0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):

  File "<ipython-input-2-06b5f17f7a22>", line 1, in <module>
    runfile('D:/Panicwq/Capsule-Forensics-master/test.py', wdir='D:/Panicwq/Capsule-Forensics-master')

  File "F:\ANACONDA\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "F:\ANACONDA\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Panicwq/Capsule-Forensics-master/test.py", line 75, in <module>
    for img_data, labels_data in tqdm(dataloader_test):

  File "F:\ANACONDA\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:

  File "F:\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 621, in __next__
    if self.rcvd_idx in self.reorder_dict:

AttributeError: '_DataLoaderIter' object has no attribute 'rcvd_idx'

**Comment by honghuy127** [comment]
Could you check the version of PyTorch you are using? If the problem still appears, please use Python 3 on Linux.
